name: Deploy to Firebase Hosting
'on':
    push:
        branches:
            - master
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm i && npm run build
            - run: npm install -g firebase-tools
            - run: firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAVIDE_GHIOTTO }}" --only hosting --project davide-ghiotto
