name: deploy-hosting
on:
    push:
        branches: [master]
        paths:
            # - 'webapp/**'
            - 'template/**'
jobs:
    deploy-hosting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
            - run: cd template && npm install && npm run build
            - uses: w9jds/firebase-action@master
            with:
                args: deploy --only hosting
            env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    ##### deploy webapp
    # deploy-hosting:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@master
    #         - uses: actions/setup-node@master
    #         - run: cd webapp && npm install
    #         - run: cd webapp && npm run build:prod
    #         - uses: w9jds/firebase-action@master
    #           with:
    #               args: deploy --only hosting
    #           env:
    #               FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
