name: deploy-hosting
on:
    push:
        branches: [master]
        paths:            
            - 'template/**'
jobs:
    deploy-hosting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
            - run: cd template && npm install && npm run build
            - uses: w9jds/firebase-action@master
            with:
                args: deploy --only hosting
            env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
