name: Deploy to Firebase Hosting Test
'on':
    push:
        branches:
            - develop
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm i && npm run build
            - run: npm install -g firebase-tools
            - run: firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAVIDE_GHIOTTO_TEST }}" --only hosting --project test-davide-ghiotto
